### ISSUE TITLE
Update JSON schema for stories 

### ISSUE THREAD

**Issue by olivif** [olivif/stories-crawler#1]
Id
Title
Summary
Body
ThumbUrl

**Comment by Rezaul** [comment]
Lets have something like this : 

{
    “stories”: [
        {
                "id": “1”,
                “title”: "Reza Rocks",
                “summary”: "Why does reza rock ?",
                “body”: “The full article“,
                “pdate” : “11/02/2015”,
                “source”: “bdnews24.com”,
	        “previewImg” : “”						 
        },

	   {
                "id": “2”,
                “title”: “Olivia Node.js Queen”,
                “summary”: “Common give me the summary“,
                “body”: “The full article“,
                “pdate” : “11/01/2015”,
                “source”: “bdnews24.com”,
	        “previewImg” : “”						 
        } 
	]
}
